CREATE TABLE [edfi].[DbSwitcher] (
	[Id] INT IDENTITY(1,1) NOT NULL,
	[Summary] VARCHAR(50),
	[CreatedDate] DATETIME NOT NULL,
	[UniqueId] UNIQUEIDENTIFIER NOT NULL,
	[IsTrue] BIT NOT NULL DEFAULT ((0)),
	CONSTRAINT [PK_DbSwitcher] PRIMARY KEY CLUSTERED ([Id])
) ON [PRIMARY]

GO